name: End to End tests

on: [push]

jobs:
  cypress-run:
    environment: staging
    runs-on: [ubuntu-20.04]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: yarn install
      - name: Run E2E tests
        run: yarn cy:run


